/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author PC
 */
public class Menu extends javax.swing.JFrame {
    
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        cadastros = new javax.swing.JMenu();
        vendedores = new javax.swing.JMenuItem();
        produto = new javax.swing.JMenuItem();
        pais = new javax.swing.JMenuItem();
        modelo = new javax.swing.JMenuItem();
        fornecedor = new javax.swing.JMenuItem();
        fabricante = new javax.swing.JMenuItem();
        estado = new javax.swing.JMenuItem();
        cliente = new javax.swing.JMenuItem();
        cidade = new javax.swing.JMenuItem();
        menu_veiculo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TranspoSystem");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2074, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1086, Short.MAX_VALUE)
        );

        cadastros.setText("Cadastros");
        cadastros.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        vendedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/vendedor.png"))); // NOI18N
        vendedores.setText("Vendedores");
        vendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendedoresActionPerformed(evt);
            }
        });
        cadastros.add(vendedores);

        produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/produto.png"))); // NOI18N
        produto.setText("Produto");
        produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoActionPerformed(evt);
            }
        });
        cadastros.add(produto);

        pais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/pais.png"))); // NOI18N
        pais.setText("Pais");
        pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paisActionPerformed(evt);
            }
        });
        cadastros.add(pais);

        modelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/modelo.png"))); // NOI18N
        modelo.setText("Modelo");
        modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloActionPerformed(evt);
            }
        });
        cadastros.add(modelo);

        fornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/fornecedor.png"))); // NOI18N
        fornecedor.setText("Fornecedor");
        fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fornecedorActionPerformed(evt);
            }
        });
        cadastros.add(fornecedor);

        fabricante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/fabricante.png"))); // NOI18N
        fabricante.setText("Fabricante");
        fabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fabricanteActionPerformed(evt);
            }
        });
        cadastros.add(fabricante);

        estado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/estado.png"))); // NOI18N
        estado.setText("Estado");
        estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoActionPerformed(evt);
            }
        });
        cadastros.add(estado);

        cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/cliente.png"))); // NOI18N
        cliente.setText("Cliente");
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });
        cadastros.add(cliente);

        cidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/cidade.png"))); // NOI18N
        cidade.setText("Cidade");
        cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadeActionPerformed(evt);
            }
        });
        cadastros.add(cidade);

        menu_veiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/veiculo.png"))); // NOI18N
        menu_veiculo.setText("Veiculos");
        menu_veiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_veiculoActionPerformed(evt);
            }
        });
        cadastros.add(menu_veiculo);

        jMenuBar1.add(cadastros);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menu_veiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_veiculoActionPerformed
        // TODO add your handling code here:
        new DialogVeiculo(this, true).setVisible(true);
    }//GEN-LAST:event_menu_veiculoActionPerformed

    private void cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadeActionPerformed
        // TODO add your handling code here:
        new DialogCidade(this, true).setVisible(true);
    }//GEN-LAST:event_cidadeActionPerformed

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        // TODO add your handling code here:
        new DialogCliente(this, true).setVisible(true);
    }//GEN-LAST:event_clienteActionPerformed

    private void estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoActionPerformed
        // TODO add your handling code here:
        new DialogEstado(this, true).setVisible(true);
    }//GEN-LAST:event_estadoActionPerformed

    private void fabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fabricanteActionPerformed
        // TODO add your handling code here:
        new DialogFabricanteVeiculo(this, true).setVisible(true);
    }//GEN-LAST:event_fabricanteActionPerformed

    private void fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fornecedorActionPerformed
        // TODO add your handling code here:
        new DialogFornecedor(this, true).setVisible(true);
    }//GEN-LAST:event_fornecedorActionPerformed

    private void modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloActionPerformed
        // TODO add your handling code here:
        new DialogModelo(this, true).setVisible(true);
    }//GEN-LAST:event_modeloActionPerformed

    private void paisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paisActionPerformed
        // TODO add your handling code here:
        new DialogPais(this, true).setVisible(true);
    }//GEN-LAST:event_paisActionPerformed

    private void produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoActionPerformed
        // TODO add your handling code here:

        new DialogProduto(this, true).setVisible(true);
    }//GEN-LAST:event_produtoActionPerformed

    private void vendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendedoresActionPerformed
        // TODO add your handling code here:
        new DialogVendedores(this, true).setVisible(true);
    }//GEN-LAST:event_vendedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu cadastros;
    private javax.swing.JMenuItem cidade;
    private javax.swing.JMenuItem cliente;
    private javax.swing.JMenuItem estado;
    private javax.swing.JMenuItem fabricante;
    private javax.swing.JMenuItem fornecedor;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menu_veiculo;
    private javax.swing.JMenuItem modelo;
    private javax.swing.JMenuItem pais;
    private javax.swing.JMenuItem produto;
    private javax.swing.JMenuItem vendedores;
    // End of variables declaration//GEN-END:variables
}
