/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.Icon;
import javax.swing.ImageIcon;




/**
 *
 * @author PC
 */
public class Menu extends javax.swing.JFrame {
    
    //ImageIcon menu = new ImageIcon(getClass().getResource("BG_home.png"));
   // JLabel label = new JLabel(menu);
    
    
    /**
     * Creates new form Menu
     */
    
    public Menu() {
        //add(menu);
        // setSize(1500,751);
         //setDefaultCloseOperation(EXIT_ON_CLOSE);
        // setLocationRelativeTo(this);
       //  setVisible(true);
        initComponents();
         
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        cadastros = new javax.swing.JMenu();
        pais = new javax.swing.JMenuItem();
        estado = new javax.swing.JMenuItem();
        cidade = new javax.swing.JMenuItem();
        cliente = new javax.swing.JMenuItem();
        fornecedor = new javax.swing.JMenuItem();
        fabricante = new javax.swing.JMenuItem();
        vendedores = new javax.swing.JMenuItem();
        produto = new javax.swing.JMenuItem();
        modelo = new javax.swing.JMenuItem();
        menu_veiculo = new javax.swing.JMenuItem();
        Carga = new javax.swing.JMenuItem();
        Menu_pedido_compra = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TranspoSystem");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/BG_home.png"))); // NOI18N

        cadastros.setText("Cadastros");
        cadastros.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        pais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/pais.png"))); // NOI18N
        pais.setText("Pais");
        pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paisActionPerformed(evt);
            }
        });
        cadastros.add(pais);

        estado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/estado.png"))); // NOI18N
        estado.setText("Estado");
        estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoActionPerformed(evt);
            }
        });
        cadastros.add(estado);

        cidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/cidade.png"))); // NOI18N
        cidade.setText("Cidade");
        cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadeActionPerformed(evt);
            }
        });
        cadastros.add(cidade);

        cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/cliente.png"))); // NOI18N
        cliente.setText("Cliente");
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });
        cadastros.add(cliente);

        fornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/fornecedor.png"))); // NOI18N
        fornecedor.setText("Fornecedor");
        fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fornecedorActionPerformed(evt);
            }
        });
        cadastros.add(fornecedor);

        fabricante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/fabricante.png"))); // NOI18N
        fabricante.setText("Fabricante");
        fabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fabricanteActionPerformed(evt);
            }
        });
        cadastros.add(fabricante);

        vendedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/vendedor.png"))); // NOI18N
        vendedores.setText("Vendedores");
        vendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendedoresActionPerformed(evt);
            }
        });
        cadastros.add(vendedores);

        produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/produto.png"))); // NOI18N
        produto.setText("Produto e Estoque");
        produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoActionPerformed(evt);
            }
        });
        cadastros.add(produto);

        modelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/modelo.png"))); // NOI18N
        modelo.setText("Modelo");
        modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloActionPerformed(evt);
            }
        });
        cadastros.add(modelo);

        menu_veiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/veiculo.png"))); // NOI18N
        menu_veiculo.setText("Veiculos");
        menu_veiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_veiculoActionPerformed(evt);
            }
        });
        cadastros.add(menu_veiculo);

        Carga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/carga.jpg"))); // NOI18N
        Carga.setText("Carga");
        cadastros.add(Carga);

        Menu_pedido_compra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/Pedido_Compra.png"))); // NOI18N
        Menu_pedido_compra.setText("Pedido de Compras");
        Menu_pedido_compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_pedido_compraActionPerformed(evt);
            }
        });
        cadastros.add(Menu_pedido_compra);

        jMenuBar1.add(cadastros);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 574, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menu_veiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_veiculoActionPerformed
        // TODO add your handling code here:
        new DialogVeiculo(this, true).setVisible(true);
    }//GEN-LAST:event_menu_veiculoActionPerformed

    private void cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadeActionPerformed
        // TODO add your handling code here:
        new DialogCidade(this, true).setVisible(true);
    }//GEN-LAST:event_cidadeActionPerformed

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        // TODO add your handling code here:
        new DialogCliente(this, true).setVisible(true);
    }//GEN-LAST:event_clienteActionPerformed

    private void estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoActionPerformed
        // TODO add your handling code here:
        new DialogEstado(this, true).setVisible(true);
    }//GEN-LAST:event_estadoActionPerformed

    private void fabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fabricanteActionPerformed
        // TODO add your handling code here:
        new DialogFabricanteVeiculo(this, true).setVisible(true);
    }//GEN-LAST:event_fabricanteActionPerformed

    private void fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fornecedorActionPerformed
        // TODO add your handling code here:
        new DialogFornecedor(this, true).setVisible(true);
    }//GEN-LAST:event_fornecedorActionPerformed

    private void modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloActionPerformed
        // TODO add your handling code here:
        new DialogModelo(this, true).setVisible(true);
    }//GEN-LAST:event_modeloActionPerformed

    private void paisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paisActionPerformed
        // TODO add your handling code here:
        new DialogPais(this, true).setVisible(true);
    }//GEN-LAST:event_paisActionPerformed

    private void produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoActionPerformed
        // TODO add your handling code here:

        new DialogProduto(this, true).setVisible(true);
    }//GEN-LAST:event_produtoActionPerformed

    private void vendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendedoresActionPerformed
        // TODO add your handling code here:
        new DialogVendedores(this, true).setVisible(true);
    }//GEN-LAST:event_vendedoresActionPerformed

    private void Menu_pedido_compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_pedido_compraActionPerformed
        // TODO add your handling code here:
        new DialogPedidoCompra(this, true).setVisible(true);
    }//GEN-LAST:event_Menu_pedido_compraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Carga;
    private javax.swing.JMenuItem Menu_pedido_compra;
    private javax.swing.JMenu cadastros;
    private javax.swing.JMenuItem cidade;
    private javax.swing.JMenuItem cliente;
    private javax.swing.JMenuItem estado;
    private javax.swing.JMenuItem fabricante;
    private javax.swing.JMenuItem fornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menu_veiculo;
    private javax.swing.JMenuItem modelo;
    private javax.swing.JMenuItem pais;
    private javax.swing.JMenuItem produto;
    private javax.swing.JMenuItem vendedores;
    // End of variables declaration//GEN-END:variables

    
}
